### ISSUE TITLE
scrollback and other features

### ISSUE THREAD

**Issue by frank604** [d8660091/st-custom#1]
Hi,

I stumbled upon your urxvt to st blog post and wanted to let you know there are a few patches at suckless website.  One of them is scroll back.  I had to enable all three.  Visit my github and look for my st-suckless repo.  If you use arch, you can pull as all my configuration is done via patching.  So you can just edit the .diff to your liking.

**Comment by d8660091** [comment]
Sorry for the delay, as I didn't anticipate someone would read it after all. Your comment is much appreciated and helpful. I have updated that post in case someone stumble again :)

**Comment by frank604** [comment]
Hey that's cool.  Yeah, it's surprising who reads the blogs.  We always assume nobody is interested.  I wanted to reach out to you in case you still use ST and were inconvenienced with the scroll back.  Editing blog is a bonus.  Have a great one.
